version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-minical}
      MYSQL_DATABASE: ${DB_DATABASE:-minical}
      MYSQL_USER: ${DB_USERNAME:-minical}
      MYSQL_PASSWORD: ${DB_PASSWORD:-minical}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - minical

  php:
    build:
      context: .
      dockerfile: docker/PHP.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - minical

  web:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "9000:80"
    volumes:
      - ./public:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - minical

  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["composer"]
    networks:
      - minical

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
    ports:
      - "9001:80"
    depends_on:
      - db
    networks:
      - minical

volumes:
  mysqldata:

networks:
  minical:
    driver: bridge
